version: '{build}'
configuration: Release

before_build:
- dotnet restore

build_script:
- dotnet build --configuration Release
  
after_test:
- dotnet pack [Main] --configuration Release --output ..

artifacts:
- path: '*.nupkg'

deploy:
  - provider: NuGet
    on:
      branch: /^(master|\d\.\d)$/
    api_key:
      secure: Q8MAs0RyoOziAiHr0nJl2WnKJm/9xqYmIinxQMBnsPzf16moCMncQmI6jtIcin5P
    artifact: /.*\.nupkg/